### PR TITLE
Refactor folder structure

### PR DESCRIPTION
**Pull request by core23**
I am targeting this branch, because this is BC.

## Changelog

```markdown
### Changed
 - Changed internal folder structure to `src`, `tests` and `docs`
```

## Subject

Adopt the new folder structure discussed on the [dev-kit](https://github.com/sonata-project/dev-kit/issues/278)

### CODE REVIEW

**Comment by core23** [comment]
Not related to this PR :/
https://travis-ci.org/sonata-project/SonataCommentBundle/builds/298074097

**Comment by greg0ire** [comment]
Please fix the conflicts, and it should pass :)

**Comment by greg0ire** [comment]
I don't need a parrot @SonataCI

**Comment by greg0ire** [comment]
Hmmmm... why is that kind of PR minor again?

**Comment by greg0ire** [comment]
Thanks @core23 !

**Comment by core23** [comment]
It's minor, because it is BC from the code perspective, but a BC break if you rely on the file structure. So we decided to make this a minor change

**Pull request merged**
