### PR TITLE
Fix Build

### PR DESCRIPTION
**Pull request by jordisala1991**
Fixed build.

### CODE REVIEW

**Comment by jordisala1991** [comment]
For some reason composer is unable to solve dependencies on `--prefer-lowest` prior this PR:

```
  Problem 1
    - jms/serializer-bundle 1.0.0 requires jms/serializer ^1.0.0 -> satisfiable by jms/serializer[1.8.1, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.8.0].
    - jms/serializer-bundle 2.1.0 requires php ^5.4|^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer-bundle 2.0.0 requires php >=5.4.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.6.2 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.6.1 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.6.0 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.5.0 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.4.2 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.4.1 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.4.0 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.3.1 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.3.0 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.2.0 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.1.0 requires php >=5.4.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.0.0 requires php >=5.4.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer-bundle 1.5.0 requires php >=5.4.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer-bundle 1.4.0 requires php >=5.4.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer-bundle 1.3.1 requires php >=5.4.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer-bundle 1.3.0 requires php >=5.4.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer-bundle 1.2.1 requires php >=5.4.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer-bundle 1.2.0 requires php >=5.4.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer-bundle 1.1.0 requires php >=5.4.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.8.1 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.8.0 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.7.1 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.7.0 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer-bundle 1.5.0 requires php >=5.4.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - jms/serializer 1.8.1 requires php >=5.5.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - Conclusion: don't install sonata-project/media-bundle 3.0.0
    - Conclusion: don't install sonata-project/media-bundle 3.1.0
    - Conclusion: don't install sonata-project/media-bundle 3.2.0
    - Conclusion: don't install sonata-project/media-bundle 3.3.0
    - sonata-project/media-bundle 3.6.0 requires jms/serializer-bundle ^0.13 || ^1.0 || ^2.0 -> satisfiable by jms/serializer-bundle[1.5.0, 0.13.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 2.0.0, 2.1.0].
    - sonata-project/media-bundle 3.5.1 requires jms/serializer-bundle ^0.13 || ^1.0 -> satisfiable by jms/serializer-bundle[1.5.0, 0.13.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0].
    - sonata-project/media-bundle 3.5.0 requires jms/serializer-bundle ^0.13 || ^1.0 -> satisfiable by jms/serializer-bundle[1.5.0, 0.13.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0].
    - sonata-project/media-bundle 3.4.0 requires jms/serializer-bundle ^0.13 || ^1.0 -> satisfiable by jms/serializer-bundle[1.5.0, 0.13.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0].
    - sonata-project/media-bundle 3.3.1 requires jms/serializer-bundle ^0.13 || ^1.0 -> satisfiable by jms/serializer-bundle[1.5.0, 0.13.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0].
    - sonata-project/media-bundle 3.6.0 requires jms/serializer-bundle ^0.13 || ^1.0 || ^2.0 -> satisfiable by jms/serializer-bundle[1.5.0, 0.13.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 2.0.0, 2.1.0].
    - Conclusion: don't install jms/serializer-bundle 0.13.0|install sonata-project/media-bundle 3.0.0|install sonata-project/media-bundle 3.1.0|install sonata-project/media-bundle 3.2.0|install sonata-project/media-bundle 3.3.0
    - Installation request for sonata-project/media-bundle ^3.0 -> satisfiable by sonata-project/media-bundle[3.0.0, 3.1.0, 3.2.0, 3.3.0, 3.3.1, 3.4.0, 3.5.0, 3.5.1, 3.6.0].
```

Looks like using media-bundle on ^3.6 solves the issue.

Why was this happening? No idea, the jms/serialized-bundle SHOULD work with 3.0.0 of media-bundle. Composer SHOULD install jms/serialized-bundle 0.13, but it's not even trying it.

**Comment by jordisala1991** [comment]
Commits are now in a better way. Please review @sonata-project/contributors

**Comment by jordisala1991** [comment]
I hate PHP 5.3... Without disabling xDebug, composer is not reliable at resolving and installing dependencies in less than 10 min.

Maybe is not a bad idea to just move PHP 5.3 to allowed failures section and just use 5.6 for the prefer-lowest

**Comment by greg0ire** [comment]
Thanks @jordisala1991

**Comment by greg0ire** [comment]
@sonata-project/contributors please review

**Pull request merged**
