### PR TITLE
Fixed paths related to SonataEasyExtendsBundle

### PR DESCRIPTION
**Pull request by vyshkant**
I am targeting this branch, because my patch is fixing the bug, arisen due to the hardcoded class-path.

## Changelog

```markdown
### Fixed
- Fixed hardcoded paths to classes in `.xml.skeleton` files of config
```

## Subject

Fixed some hardcoded paths, which become invalid after enabling
the '--namespace' option in SonataEasyExtendsBundle's last release
(https://github.com/sonata-project/SonataEasyExtendsBundle/releases/tag/2.2.0)

See also: https://github.com/sonata-project/SonataMediaBundle/pull/1250

### CODE REVIEW

**Comment by vyshkant** [comment]
Any ideas what should be done to fix travis build?

**Comment by greg0ire** [comment]
I'm retrying this particular job, but we may have to bump some dependency.

**Comment by jordisala1991** [comment]
For some reason it is unable to install deps on prefer-lower

**Comment by vyshkant** [comment]
Is the problem in the commit? Should I remove added dependency? (Not sure this is correct to store SonataEasyExtendsBundle's skeletons and not be dependent on this bundle)

**Comment by vyshkant** [comment]
@greg0ire @jordisala1991 I have downgraded sonata-project/easy-extends-bundle dependency to original version and after that all checks have passed.

Does anybody understand why?

Now this patch can be merged?

**Comment by greg0ire** [comment]
> Does anybody understand why?

I don't, but it if was prefer-lowest that failed, it means 2.2 is incompatible with one of the lowest versions of the deps, while 2.1 isn't. Strange, but not a big deal, so let's merge.

**Comment by vyshkant** [comment]
> it means 2.2 is incompatible with one of the lowest versions of the deps

The most strange thing is that the reason of build fail was "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself", not the "Dependency resolution error".

**Comment by greg0ire** [comment]
It means the resolution was stalled for 10mn. Can happen when the problem is complex, and I think it is when using prefer lowest.

**Comment by vyshkant** [comment]
Yes, it was prefer-lowest.

**Pull request merged**
